### PR TITLE
Too many JS errors. What's wrong??

### PR DESCRIPTION
**Pull request by with-a-k**
I'm getting a ton of console errors when I try to connect to the server. What's wrong in node_communicator.js? Am I missing packages I need for this end? @stevekinney

### CODE REVIEW

**Comment by stevekinney** [comment]
Whoa. `node_modules` needs to be in `.gitignore`.

**Comment by stevekinney** [comment]
Pretty sure these need to be separate projects. It looks like your project is inside of a Rails application.

**Comment by with-a-k** [comment]
oh, huh. So where do I put the "var socket = io(‘http://[your-node-server]')", then?

**Comment by stevekinney** [comment]
Just grab the client library.

**Comment by with-a-k** [comment]
...and where's that.

**Comment by stevekinney** [comment]
http://socket.io/download/ http://socket.io/download/

**Pull request merged**
